version: '3.8'
services:

  backend:
    build: ../backend
    ports:
      - "8010:8010"
    restart: always
    container_name: fastapi_backend

  frontend:
    build: ../frontend
    ports:
      - "3010:3000"
    stdin_open: true
    tty: true 
    restart: always
    container_name: react_frontend
